```
TestSetException
```

테스트 세트가 완료되었지만 모든 테스트가 통과하지 않았을 때 발생합니다.
