```
ParallelProcessingTools.inner_exception(err)
```

Replaces exceptions like a `TaskFailedException` or a `RemoteException` with their underlying cause. Leaves other exceptions unchanged.
